name: PR Docs Link Check

on:
  pull_request:

jobs:
  check-docs-links:
    uses: papermoonio/workflows/.github/workflows/core-pr-link-checker.yml@main
    with:
      mkdocs_repo: papermoonio/polkadot-mkdocs
      docs_repo: polkadot-developers/polkadot-docs
      docs_checkout: polkadot-docs
      url: https://docs.polkadot.com
    secrets:
      GH_TOKEN: ${{ secrets.GH_PR_404_CHECKER }}
